# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
