# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRM', '0004_auto_20171016_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecase',
            name='mac_list',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='key',
            field=models.CharField(max_length=300),
        ),
    ]
