# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRM', '0005_auto_20171016_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.FileField(null=True, upload_to='ebook'),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRM.Book'),
        ),
    ]
