# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRM', '0006_auto_20171020_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.FileField(blank=True, upload_to='ebook'),
        ),
        migrations.AlterField(
            model_name='purchasecase',
            name='mac_list',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
